const CARDS = [
    // Greetings & Basics
    { id: 1, en: "Hello!", ru: "Привет!", pronun: "Pri-vyét!", literal: "(informal greeting)", note: "Use Здравствуйте (Zdráv-stvuy-tye) in formal situations." },
    { id: 2, en: "Good morning!", ru: "Доброе утро!", pronun: "Dó-bro-ye út-ro!", literal: "Good morning!", note: "" },
    { id: 3, en: "Good afternoon!", ru: "Добрый день!", pronun: "Dób-riy dyen'!", literal: "Good day!", note: "" },
    { id: 4, en: "Good evening!", ru: "Добрый вечер!", pronun: "Dób-riy vyé-cher!", literal: "Good evening!", note: "" },
    { id: 5, en: "Goodbye!", ru: "До свидания!", pronun: "Da svi-dá-ni-ya!", literal: "Until (we) meet again!", note: "Пока (Pa-ká) is informal." },
    { id: 6, en: "How are you?", ru: "Как дела?", pronun: "Kak de-lá?", literal: "How (are your) affairs?", note: "Как ты? (Kak tý?) is very informal." },
    { id: 7, en: "I'm fine, thanks.", ru: "Хорошо, спасибо.", pronun: "Kha-ra-shó, spa-sí-ba.", literal: "Good, thank you.", note: "" },
    { id: 8, en: "What is your name?", ru: "Как вас зовут?", pronun: "Kak vas za-vút?", literal: "How are you called?", note: "Как тебя зовут? (Kak te-byá?) is informal." },
    { id: 9, en: "My name is...", ru: "Меня зовут...", pronun: "Me-nyá za-vút...", literal: "Me they-call...", note: "" },
    { id: 10, en: "Nice to meet you!", ru: "Приятно познакомиться!", pronun: "Pri-yát-na paz-na-kó-mi-tsya!", literal: "Pleasant to acquaint!", note: "" },

    // Politeness
    { id: 11, en: "Please.", ru: "Пожалуйста.", pronun: "Pa-zhá-luy-sta.", literal: "Please.", note: "Also means 'You're welcome'." },
    { id: 12, en: "Thank you.", ru: "Спасибо.", pronun: "Spa-sí-ba.", literal: "Thank you.", note: "Большое спасибо = Thank you very much." },
    { id: 13, en: "You're welcome.", ru: "Пожалуйста.", pronun: "Pa-zhá-luy-sta.", literal: "Please / You're welcome.", note: "Same word as 'please'." },
    { id: 14, en: "Excuse me.", ru: "Извините.", pronun: "Iz-vi-ní-tye.", literal: "Excuse (me).", note: "Прости (Pra-stí) is informal." },
    { id: 15, en: "I'm sorry.", ru: "Мне жаль.", pronun: "Mnye zhal'.", literal: "To me (it is) a pity.", note: "Простите = Forgive me (formal)." },
    { id: 16, en: "No problem!", ru: "Ничего страшного!", pronun: "Ni-che-vó strásh-na-va!", literal: "Nothing terrible!", note: "" },

    // Yes / No / Questions
    { id: 17, en: "Yes.", ru: "Да.", pronun: "Da.", literal: "Yes.", note: "" },
    { id: 18, en: "No.", ru: "Нет.", pronun: "Nyet.", literal: "No.", note: "" },
    { id: 19, en: "Maybe.", ru: "Может быть.", pronun: "Mó-zhet byt'.", literal: "Might be.", note: "" },
    { id: 20, en: "I don't know.", ru: "Я не знаю.", pronun: "Ya nye zná-yu.", literal: "I not know.", note: "" },
    { id: 21, en: "I understand.", ru: "Я понимаю.", pronun: "Ya pa-ni-má-yu.", literal: "I understand.", note: "" },
    { id: 22, en: "I don't understand.", ru: "Я не понимаю.", pronun: "Ya nye pa-ni-má-yu.", literal: "I not understand.", note: "" },
    { id: 23, en: "Do you speak English?", ru: "Вы говорите по-английски?", pronun: "Vy ga-va-rí-tye pa ang-líy-ski?", literal: "You speak in-English?", note: "" },
    { id: 24, en: "I speak a little Russian.", ru: "Я немного говорю по-русски.", pronun: "Ya neem-nó-ga ga-va-ryú pa-rús-ki.", literal: "I a-little speak in-Russian.", note: "" },
    { id: 25, en: "Could you repeat that?", ru: "Повторите, пожалуйста.", pronun: "Paf-ta-rí-tye, pa-zhá-luy-sta.", literal: "Repeat, please.", note: "" },
    { id: 26, en: "Speak slowly, please.", ru: "Говорите медленнее.", pronun: "Ga-va-rí-tye myéd-le-ne-ye.", literal: "Speak more-slowly.", note: "" },

    // Numbers & Time
    { id: 27, en: "How old are you?", ru: "Сколько вам лет?", pronun: "Skól-ka vam lyet?", literal: "How many you years?", note: "Use ВАМ for strangers, ТЕБЕ for friends." },
    { id: 28, en: "What time is it?", ru: "Который час?", pronun: "Ka-tó-ry chas?", literal: "Which hour?", note: "" },
    { id: 29, en: "What day is today?", ru: "Какой сегодня день?", pronun: "Ka-kóy se-vód-nya dyen'?", literal: "Which today day?", note: "" },
    { id: 30, en: "Today is Monday.", ru: "Сегодня понедельник.", pronun: "Se-vód-nya pa-ne-dyél-nik.", literal: "Today (is) Monday.", note: "" },

    // Directions & Location
    { id: 31, en: "Where is the bathroom?", ru: "Где туалет?", pronun: "Gdye tu-a-lyét?", literal: "Where (is) toilet?", note: "" },
    { id: 32, en: "Where is the metro?", ru: "Где метро?", pronun: "Gdye met-ró?", literal: "Where (is) metro?", note: "" },
    { id: 33, en: "Turn left.", ru: "Поверните налево.", pronun: "Pa-ver-ní-tye na-lyé-va.", literal: "Turn to-left.", note: "" },
    { id: 34, en: "Turn right.", ru: "Поверните направо.", pronun: "Pa-ver-ní-tye na-prá-va.", literal: "Turn to-right.", note: "" },
    { id: 35, en: "Go straight ahead.", ru: "Идите прямо.", pronun: "I-dí-tye prya-ma.", literal: "Go straight.", note: "" },
    { id: 36, en: "It is near / far.", ru: "Это близко / далеко.", pronun: "É-ta blyís-ka / da-le-kó.", literal: "This near / far.", note: "" },
    { id: 37, en: "I am lost.", ru: "Я заблудился.", pronun: "Ya za-blu-díl-sya.", literal: "I got-lost.", note: "Woman says: заблудилась (za-blu-dí-las')." },

    // Shopping
    { id: 38, en: "How much does this cost?", ru: "Сколько это стоит?", pronun: "Skól-ka é-ta stó-it?", literal: "How-much this costs?", note: "" },
    { id: 39, en: "That is too expensive.", ru: "Это слишком дорого.", pronun: "É-ta slísh-kam dó-ra-ga.", literal: "This too expensive.", note: "" },
    { id: 40, en: "Do you have...?", ru: "У вас есть...?", pronun: "U vas yest'...?", literal: "At you there-is...?", note: "" },
    { id: 41, en: "I'll take this.", ru: "Я возьму это.", pronun: "Ya vaz'-mú é-ta.", literal: "I will-take this.", note: "" },
    { id: 42, en: "Can I pay by card?", ru: "Можно платить картой?", pronun: "Mózh-na pla-tít' kár-tay?", literal: "Possible to-pay by-card?", note: "" },
    { id: 43, en: "The receipt, please.", ru: "Чек, пожалуйста.", pronun: "Chyek, pa-zhá-luy-sta.", literal: "Receipt, please.", note: "" },

    // Food & Drinks
    { id: 44, en: "I am hungry.", ru: "Я хочу есть.", pronun: "Ya kha-chú yest'.", literal: "I want to-eat.", note: "" },
    { id: 45, en: "I am thirsty.", ru: "Я хочу пить.", pronun: "Ya kha-chú pit'.", literal: "I want to-drink.", note: "" },
    { id: 46, en: "A table for two, please.", ru: "Столик на двоих, пожалуйста.", pronun: "Stó-lik na dva-íkh, pa-zhá-luy-sta.", literal: "Table for two, please.", note: "" },
    { id: 47, en: "The menu, please.", ru: "Меню, пожалуйста.", pronun: "Me-nyú, pa-zhá-luy-sta.", literal: "Menu, please.", note: "" },
    { id: 48, en: "I'd like water, please.", ru: "Воду, пожалуйста.", pronun: "Vó-du, pa-zhá-luy-sta.", literal: "Water, please.", note: "" },
    { id: 49, en: "It's delicious!", ru: "Очень вкусно!", pronun: "Ó-chen' fkús-na!", literal: "Very tasty!", note: "" },
    { id: 50, en: "The bill, please.", ru: "Счёт, пожалуйста.", pronun: "Shchyot, pa-zhá-luy-sta.", literal: "Bill, please.", note: "" },

    // Transport
    { id: 51, en: "Where does this bus go?", ru: "Куда идёт этот автобус?", pronun: "Ku-dá i-dyót é-tat af-tó-bus?", literal: "Where goes this bus?", note: "" },
    { id: 52, en: "One ticket to..., please.", ru: "Один билет до..., пожалуйста.", pronun: "A-dín bi-lyét da..., pa-zhá-luy-sta.", literal: "One ticket to..., please.", note: "" },
    { id: 53, en: "When does the train leave?", ru: "Когда отходит поезд?", pronun: "Kag-dá at-khó-dit pó-yezd?", literal: "When departs train?", note: "" },
    { id: 54, en: "I need a taxi.", ru: "Мне нужно такси.", pronun: "Mnye núzh-na tak-sí.", literal: "To-me needed taxi.", note: "" },
    { id: 55, en: "Take me to this address.", ru: "Отвезите меня по этому адресу.", pronun: "At-ve-zí-tye me-nyá pa é-ta-mu á-dre-su.", literal: "Drive-me by this address.", note: "" },

    // Health
    { id: 56, en: "I need a doctor.", ru: "Мне нужен врач.", pronun: "Mnye nú-zhen vrach.", literal: "To-me needed doctor.", note: "" },
    { id: 57, en: "Call an ambulance!", ru: "Вызовите скорую помощь!", pronun: "Vý-za-vi-tye skó-ru-yu pó-mash'!", literal: "Call quick help!", note: "" },
    { id: 58, en: "I have a headache.", ru: "У меня болит голова.", pronun: "U me-nyá ba-lít ga-la-vá.", literal: "At me hurts head.", note: "" },
    { id: 59, en: "I am allergic to...", ru: "У меня аллергия на...", pronun: "U me-nyá a-ler-gí-ya na...", literal: "At me allergy to...", note: "" },
    { id: 60, en: "Where is the pharmacy?", ru: "Где аптека?", pronun: "Gdye ap-tyé-ka?", literal: "Where (is) pharmacy?", note: "" },

    // Accommodation
    { id: 61, en: "I have a reservation.", ru: "У меня есть бронь.", pronun: "U me-nyá yest' bron'.", literal: "At me there-is reservation.", note: "" },
    { id: 62, en: "Is breakfast included?", ru: "Завтрак включён?", pronun: "Závt-rak fklyú-chon?", literal: "Breakfast included?", note: "" },
    { id: 63, en: "The room key, please.", ru: "Ключ от номера, пожалуйста.", pronun: "Klyuch at nó-me-ra, pa-zhá-luy-sta.", literal: "Key from room, please.", note: "" },
    { id: 64, en: "My room is dirty.", ru: "В моём номере грязно.", pronun: "V ma-yóm nó-me-rye gryáz-na.", literal: "In my room dirty.", note: "" },
    { id: 65, en: "I'd like to check out.", ru: "Я хочу выехать.", pronun: "Ya kha-chú vý-ye-khat'.", literal: "I want to-check-out.", note: "" },

    // Work & Study
    { id: 66, en: "What do you do for work?", ru: "Кем вы работаете?", pronun: "Kyem vy ra-bó-ta-ye-tye?", literal: "(As) whom you work?", note: "" },
    { id: 67, en: "I am a student.", ru: "Я студент.", pronun: "Ya stu-dyént.", literal: "I (am) student.", note: "Woman says: студентка (stu-dyént-ka)." },
    { id: 68, en: "I work at...", ru: "Я работаю в...", pronun: "Ya ra-bó-ta-yu v...", literal: "I work in...", note: "" },
    { id: 69, en: "I have a meeting.", ru: "У меня встреча.", pronun: "U me-nyá fstrye-cha.", literal: "At me meeting.", note: "" },
    { id: 70, en: "Send me an email.", ru: "Пришлите мне письмо на почту.", pronun: "Prish-lí-tye mnye pis'-mó na poch-tu.", literal: "Send me letter to mail.", note: "" },

    // Family & People
    { id: 71, en: "This is my friend.", ru: "Это мой друг.", pronun: "É-ta moy drug.", literal: "This my friend.", note: "Female friend: подруга (pad-rú-ga)." },
    { id: 72, en: "I have two children.", ru: "У меня двое детей.", pronun: "U me-nyá dvó-ye de-tyéy.", literal: "At me two-of children.", note: "" },
    { id: 73, en: "How old is your child?", ru: "Сколько лет вашему ребёнку?", pronun: "Skól-ka lyet vá-she-mu re-byón-ku?", literal: "How-many years your child?", note: "" },
    { id: 74, en: "I am married.", ru: "Я женат.", pronun: "Ya zhe-nát.", literal: "I married.", note: "Woman says: замужем (zá-mu-zhem)." },
    { id: 75, en: "I am single.", ru: "Я не женат.", pronun: "Ya nye zhe-nát.", literal: "I not married.", note: "Woman says: не замужем (nye zá-mu-zhem)." },

    // Weather
    { id: 76, en: "What's the weather like?", ru: "Какая погода?", pronun: "Ka-ká-ya pa-gó-da?", literal: "What (kind) weather?", note: "" },
    { id: 77, en: "It's hot today.", ru: "Сегодня жарко.", pronun: "Se-vód-nya zhár-ka.", literal: "Today hot.", note: "" },
    { id: 78, en: "It's cold today.", ru: "Сегодня холодно.", pronun: "Se-vód-nya khó-lad-na.", literal: "Today cold.", note: "" },
    { id: 79, en: "It's raining.", ru: "Идёт дождь.", pronun: "I-dyót dozh'd'.", literal: "Goes rain.", note: "Идёт literally means 'goes' — rain 'goes' in Russian." },
    { id: 80, en: "It's snowing.", ru: "Идёт снег.", pronun: "I-dyót snyeg.", literal: "Goes snow.", note: "" },

    // Emotions & Opinions
    { id: 81, en: "I like this.", ru: "Мне нравится это.", pronun: "Mnye nrá-vi-tsya é-ta.", literal: "To-me pleases this.", note: "" },
    { id: 82, en: "I don't like this.", ru: "Мне не нравится это.", pronun: "Mnye nye nrá-vi-tsya é-ta.", literal: "To-me not pleases this.", note: "" },
    { id: 83, en: "I am happy.", ru: "Я счастлив.", pronun: "Ya shás-liv.", literal: "I happy.", note: "Woman says: счастлива (shás-li-va)." },
    { id: 84, en: "I am tired.", ru: "Я устал.", pronun: "Ya us-tál.", literal: "I got-tired.", note: "Woman says: устала (us-tá-la)." },
    { id: 85, en: "I am bored.", ru: "Мне скучно.", pronun: "Mnye skúch-na.", literal: "To-me boring.", note: "" },
    { id: 86, en: "That's interesting!", ru: "Это интересно!", pronun: "É-ta in-te-ryes-na!", literal: "This interesting!", note: "" },
    { id: 87, en: "That's great!", ru: "Отлично!", pronun: "At-lích-na!", literal: "Excellent!", note: "Классно (Klás-na) = Cool! (informal)" },

    // Technology & Everyday
    { id: 88, en: "Do you have Wi-Fi?", ru: "Есть ли у вас Wi-Fi?", pronun: "Yest' li u vas vay-fay?", literal: "There-is whether at you Wi-Fi?", note: "" },
    { id: 89, en: "What is the password?", ru: "Какой пароль?", pronun: "Ka-kóy pa-ról'?", literal: "What (is) password?", note: "" },
    { id: 90, en: "My phone is dead.", ru: "Мой телефон разрядился.", pronun: "Moy te-le-fón raz-rya-díl-sya.", literal: "My phone discharged.", note: "" },
    { id: 91, en: "Can I charge my phone?", ru: "Можно зарядить телефон?", pronun: "Mózh-na za-rya-dít' te-le-fón?", literal: "Possible to-charge phone?", note: "" },
    { id: 92, en: "Take a photo, please.", ru: "Сфотографируйте меня, пожалуйста.", pronun: "Sfo-ta-gra-fí-ruy-tye me-nyá, pa-zhá-luy-sta.", literal: "Photograph me, please.", note: "" },

    // Social
    { id: 93, en: "Happy birthday!", ru: "С днём рождения!", pronun: "S dnyom razh-dyé-ni-ya!", literal: "With day of-birth!", note: "" },
    { id: 94, en: "Cheers! (toast)", ru: "За здоровье!", pronun: "Za zda-ró-vye!", literal: "To (your) health!", note: "" },
    { id: 95, en: "Good luck!", ru: "Удачи!", pronun: "U-dá-chi!", literal: "(Of) luck!", note: "" },
    { id: 96, en: "Have a nice trip!", ru: "Счастливого пути!", pronun: "Shchas-lí-va-va pu-tí!", literal: "Happy journey!", note: "" },
    { id: 97, en: "Let's go!", ru: "Поехали!", pronun: "Pa-yé-kha-li!", literal: "We-went!", note: "Famous phrase said by Gagarin at launch." },
    { id: 98, en: "Wait a moment.", ru: "Подождите, пожалуйста.", pronun: "Pa-dazh-dí-tye, pa-zhá-luy-sta.", literal: "Wait, please.", note: "" },
    { id: 99, en: "Help!", ru: "Помогите!", pronun: "Pa-ma-gí-tye!", literal: "Help (me)!", note: "" },
    { id: 100, en: "I love you.", ru: "Я тебя люблю.", pronun: "Ya te-byá lyub-lyú.", literal: "I you love.", note: "Я вас люблю (formal/plural). The most important phrase!" },
];

// ── 100 Slang & Real-World Phrases ─────────────────────────────────────────
const SLANG = [
    { id: 101, slang: true, en: "Cool! / Awesome!", ru: "Круто!", pronun: "Krú-ta!", literal: "Steep / Cool!", note: "The most universal Russian slang word. Works for almost anything impressive." },
    { id: 102, slang: true, en: "No way! / Get out!", ru: "Да ладно!", pronun: "Da lád-na!", literal: "Yes, come on!", note: "Said with disbelief. Equivalent to 'You're kidding me!'" },
    { id: 103, slang: true, en: "Let's go! / Come on!", ru: "Давай!", pronun: "Da-váy!", literal: "Give!", note: "Extremely versatile: agree, encourage, hurry up, or say bye — depends on context." },
    { id: 104, slang: true, en: "For real? / Seriously?", ru: "Серьёзно?", pronun: "Ser'-yóz-na?", literal: "Seriously?", note: "" },
    { id: 105, slang: true, en: "Whatever / I don't care.", ru: "Мне всё равно.", pronun: "Mnye fsyo rav-nó.", literal: "To me all the-same.", note: "" },
    { id: 106, slang: true, en: "It doesn't matter.", ru: "Неважно.", pronun: "Ne-vázhna.", literal: "Not important.", note: "Shorter and more casual than 'Мне всё равно'." },
    { id: 107, slang: true, en: "Chill out / Relax.", ru: "Успокойся.", pronun: "Us-pa-kóy-sya.", literal: "Calm yourself.", note: "Informal. Use with friends only." },
    { id: 108, slang: true, en: "Stop it! / Cut it out!", ru: "Хватит!", pronun: "Khvá-tit!", literal: "Enough!", note: "Works as 'That's enough!' or 'Stop it!'" },
    { id: 109, slang: true, en: "That's nonsense / rubbish.", ru: "Ерунда.", pronun: "Ye-run-dá.", literal: "Nonsense.", note: "Бред (Bryed) is stronger slang for 'utter nonsense / garbage'." },
    { id: 110, slang: true, en: "I'm broke / out of money.", ru: "У меня нет денег.", pronun: "U me-nyá nyet dyé-nek.", literal: "At me no money.", note: "Слился (Slíl-sya) = slang for 'went broke / bailed'." },
    { id: 111, slang: true, en: "I'm bored to death.", ru: "Мне до смерти скучно.", pronun: "Mnye da smyer-ti skúch-na.", literal: "To-me to-death boring.", note: "" },
    { id: 112, slang: true, en: "What's going on? / What's up?", ru: "Что происходит?", pronun: "Shto pra-is-khó-dit?", literal: "What is happening?", note: "Что случилось? (Shto slu-chí-las'?) = What happened?" },
    { id: 113, slang: true, en: "I'm in! / Count me in.", ru: "Я в деле!", pronun: "Ya v dyé-lye!", literal: "I in the-deal!", note: "" },
    { id: 114, slang: true, en: "Forget it / Never mind.", ru: "Забудь.", pronun: "Za-bud'.", literal: "Forget (it).", note: "Informal command." },
    { id: 115, slang: true, en: "He/She is lying.", ru: "Он / Она врёт.", pronun: "On / A-ná vryot.", literal: "He / She lies.", note: "" },
    { id: 116, slang: true, en: "Are you kidding me?", ru: "Ты шутишь?", pronun: "Ty shú-tish'?", literal: "You joke?", note: "" },
    { id: 117, slang: true, en: "I have no idea.", ru: "Понятия не имею.", pronun: "Pa-nyá-ti-ya nye i-myé-yu.", literal: "Notion not have-I.", note: "Без понятия (Byez pa-nyá-ti-ya) is the shorter slang version." },
    { id: 118, slang: true, en: "Dude / Man (address)", ru: "Чувак", pronun: "Chu-vák", literal: "Dude", note: "Female equivalent: чувиха (chu-ví-kha). Very casual." },
    { id: 119, slang: true, en: "Friend / Buddy", ru: "Приятель", pronun: "Pri-yá-tel'", literal: "Pleasant-one", note: "Кореш (Kó-resh) is more street-slang for close buddy." },
    { id: 120, slang: true, en: "It's a mess / chaos here.", ru: "Здесь бардак.", pronun: "Zdyes' bar-dák.", literal: "Here bawdy-house.", note: "Бардак literally means brothel but colloquially means total mess/chaos." },
    { id: 121, slang: true, en: "That's so cool / sick!", ru: "Огонь!", pronun: "A-gón'!", literal: "Fire!", note: "Literally 'fire'. Used like 'fire' in English slang — great, awesome." },
    { id: 122, slang: true, en: "That's lame / trash.", ru: "Отстой.", pronun: "At-stóy.", literal: "(What has) settled/sunk.", note: "Literally: sediment. Means something is terrible/boring." },
    { id: 123, slang: true, en: "I'm tired of it.", ru: "Надоело.", pronun: "Na-da-yé-la.", literal: "It has bored (me).", note: "" },
    { id: 124, slang: true, en: "I got it / Understood.", ru: "Понял. / Поняла.", pronun: "Pó-nyal. / Pan-ya-lá.", literal: "Understood (m/f).", note: "Male speaker: понял. Female: поняла." },
    { id: 125, slang: true, en: "No worries / It's fine.", ru: "Всё нормально.", pronun: "Fsyo nor-mál'-na.", literal: "Everything normally.", note: "Norm (Норм) is the ultra-short texting version." },
    { id: 126, slang: true, en: "What a coincidence!", ru: "Какое совпадение!", pronun: "Ka-kó-ye saf-pa-dyé-ni-ye!", literal: "What coincidence!", note: "" },
    { id: 127, slang: true, en: "It went well / worked out.", ru: "Получилось!", pronun: "Pa-lu-chí-las'!", literal: "It worked-out!", note: "" },
    { id: 128, slang: true, en: "Fail / It didn't work.", ru: "Облом.", pronun: "Ab-lóm.", literal: "Break-off.", note: "Also used as 'That's a bummer / what a letdown'." },
    { id: 129, slang: true, en: "To hang out / chill.", ru: "Тусоваться.", pronun: "Tu-sa-vá-tsya.", literal: "To party/hang.", note: "Тусовка (tu-sóv-ka) = a gathering, party, or scene." },
    { id: 130, slang: true, en: "Let's hang out!", ru: "Потусуемся!", pronun: "Pa-tu-sú-em-sya!", literal: "Let's-hang!", note: "" },
    { id: 131, slang: true, en: "I overslept.", ru: "Я проспал.", pronun: "Ya pra-spál.", literal: "I slept-through.", note: "Female: проспала (pra-spa-lá)." },
    { id: 132, slang: true, en: "I'm running late.", ru: "Я опаздываю.", pronun: "Ya a-páz-dy-va-yu.", literal: "I am-late.", note: "" },
    { id: 133, slang: true, en: "Traffic jam.", ru: "Пробки.", pronun: "Próp-ki.", literal: "Corks.", note: "Russians say 'corks' for traffic jams — like corks in a bottle." },
    { id: 134, slang: true, en: "Stuck in traffic.", ru: "Стою в пробках.", pronun: "Sta-yú v próp-kakh.", literal: "Standing in corks.", note: "" },
    { id: 135, slang: true, en: "I'll be there soon.", ru: "Скоро буду.", pronun: "Skó-ra bú-du.", literal: "Soon will-be.", note: "Very common text message phrase." },
    { id: 136, slang: true, en: "I'm on my way.", ru: "Я уже еду.", pronun: "Ya u-zhé yé-du.", literal: "I already go.", note: "" },
    { id: 137, slang: true, en: "Where are you?", ru: "Ты где?", pronun: "Ty gdye?", literal: "You where?", note: "Very common texting phrase." },
    { id: 138, slang: true, en: "Almost there.", ru: "Почти на месте.", pronun: "Pach-tí na myés-tye.", literal: "Almost at place.", note: "" },
    { id: 139, slang: true, en: "I'll call you back.", ru: "Я тебе перезвоню.", pronun: "Ya te-byé pe-re-zva-nyú.", literal: "I to-you will-call-back.", note: "" },
    { id: 140, slang: true, en: "My battery is dying.", ru: "Телефон садится.", pronun: "Te-le-fón sa-dí-tsya.", literal: "Phone is-sitting-down.", note: "Literally 'phone is sitting down' — Russian slang for battery dying." },
    { id: 141, slang: true, en: "I'm hungry as a wolf.", ru: "Я голодный как волк.", pronun: "Ya ga-lód-ny kak volk.", literal: "I hungry as wolf.", note: "Russian idiom for extreme hunger." },
    { id: 142, slang: true, en: "Let's grab a bite.", ru: "Давай перекусим.", pronun: "Da-váy pe-re-kú-sim.", literal: "Let's have a-snack.", note: "" },
    { id: 143, slang: true, en: "Bon appétit!", ru: "Приятного аппетита!", pronun: "Pri-yát-na-va a-pe-tí-ta!", literal: "Pleasant appetite!", note: "Said before eating. Russians always say this." },
    { id: 144, slang: true, en: "It tastes awful.", ru: "Это невкусно.", pronun: "É-ta nyef-kús-na.", literal: "This not-tasty.", note: "" },
    { id: 145, slang: true, en: "I'm stuffed / full.", ru: "Я наелся.", pronun: "Ya na-yél-sya.", literal: "I ate-my-fill.", note: "Female: наелась (na-yé-las')." },
    { id: 146, slang: true, en: "Let's split the bill.", ru: "Давайте разделим счёт.", pronun: "Da-váy-tye raz-dyé-lim shchyot.", literal: "Let's divide the bill.", note: "" },
    { id: 147, slang: true, en: "Treat me! / Your round.", ru: "Угощаешь?", pronun: "U-gash-chá-yesh'?", literal: "You-treating?", note: "" },
    { id: 148, slang: true, en: "That was a great evening!", ru: "Отличный вечер!", pronun: "At-lích-ny vyé-cher!", literal: "Excellent evening!", note: "" },
    { id: 149, slang: true, en: "I need to go home.", ru: "Мне нужно домой.", pronun: "Mnye núzh-na da-móy.", literal: "To-me needed home.", note: "" },
    { id: 150, slang: true, en: "Get home safe!", ru: "Добирайся домой осторожно!", pronun: "Da-bi-ráy-sya da-móy as-ta-rózh-na!", literal: "Get-home carefully!", note: "" },
    { id: 151, slang: true, en: "I have a hangover.", ru: "У меня похмелье.", pronun: "U me-nyá pakhmyél'-ye.", literal: "At me hangover.", note: "" },
    { id: 152, slang: true, en: "Let's not talk about it.", ru: "Не будем об этом.", pronun: "Nye bú-dem ab é-tam.", literal: "Let's-not about this.", note: "" },
    { id: 153, slang: true, en: "Mind your own business.", ru: "Не твоё дело.", pronun: "Nye tva-yó dyé-la.", literal: "Not your business.", note: "" },
    { id: 154, slang: true, en: "Leave me alone.", ru: "Оставь меня в покое.", pronun: "As-táv' me-nyá f pa-kó-ye.", literal: "Leave me in peace.", note: "" },
    { id: 155, slang: true, en: "You're getting on my nerves.", ru: "Ты мне надоел.", pronun: "Ty mnye na-da-yél.", literal: "You to-me have-bored.", note: "Female speaker/subject shifts the ending." },
    { id: 156, slang: true, en: "That's not your problem.", ru: "Это не твоя проблема.", pronun: "É-ta nye tva-yá prab-lyé-ma.", literal: "This not your problem.", note: "" },
    { id: 157, slang: true, en: "We need to talk.", ru: "Нам нужно поговорить.", pronun: "Nam núzh-na pa-ga-va-rít'.", literal: "Us needed to-talk.", note: "A phrase that rarely brings good news in any language." },
    { id: 158, slang: true, en: "Don't worry!", ru: "Не переживай!", pronun: "Nye pe-re-zhi-váy!", literal: "Don't over-live-it!", note: "Literally 'don't experience too much'. Common Russian comfort phrase." },
    { id: 159, slang: true, en: "Everything will be okay.", ru: "Всё будет хорошо.", pronun: "Fsyo bú-det kha-ra-shó.", literal: "Everything will be good.", note: "A classic Russian reassurance." },
    { id: 160, slang: true, en: "It could be worse.", ru: "Могло быть хуже.", pronun: "Mag-ló byt' khú-zhe.", literal: "Could be worse.", note: "" },
    { id: 161, slang: true, en: "What a nightmare!", ru: "Какой кошмар!", pronun: "Ka-kóy kash-már!", literal: "What nightmare!", note: "" },
    { id: 162, slang: true, en: "I'm in trouble.", ru: "Я в беде.", pronun: "Ya v be-dyé.", literal: "I in trouble.", note: "Я попал (Ya pa-pál) = I'm in deep trouble / I got caught." },
    { id: 163, slang: true, en: "Let's figure it out.", ru: "Давайте разберёмся.", pronun: "Da-váy-tye raz-be-ryóm-sya.", literal: "Let's sort-it-out.", note: "" },
    { id: 164, slang: true, en: "It all worked out!", ru: "Всё обошлось!", pronun: "Fsyo a-ba-shlós'!", literal: "Everything went-around!", note: "" },
    { id: 165, slang: true, en: "You're right.", ru: "Ты прав.", pronun: "Ty prav.", literal: "You right.", note: "Female: ты права (ty pra-vá)." },
    { id: 166, slang: true, en: "You're wrong.", ru: "Ты не прав.", pronun: "Ty nye prav.", literal: "You not right.", note: "Female: ты не права (nye pra-vá)." },
    { id: 167, slang: true, en: "I agree.", ru: "Я согласен.", pronun: "Ya sag-lá-sen.", literal: "I in-agreement.", note: "Female: согласна (sag-lás-na)." },
    { id: 168, slang: true, en: "I disagree.", ru: "Я не согласен.", pronun: "Ya nye sag-lá-sen.", literal: "I not in-agreement.", note: "" },
    { id: 169, slang: true, en: "Let me think.", ru: "Дай подумаю.", pronun: "Day pa-dú-ma-yu.", literal: "Let (me) think.", note: "" },
    { id: 170, slang: true, en: "Are you serious right now?", ru: "Ты серьёзно сейчас?", pronun: "Ty ser'-yóz-na sey-chás?", literal: "You seriously now?", note: "" },
    { id: 171, slang: true, en: "What are you doing tonight?", ru: "Что делаешь вечером?", pronun: "Shto dyé-la-yesh' vyé-che-ram?", literal: "What doing (you) evening?", note: "" },
    { id: 172, slang: true, en: "Are you free on Saturday?", ru: "Ты свободен в субботу?", pronun: "Ty sva-bó-den v su-bó-tu?", literal: "You free on Saturday?", note: "Female: свободна (sva-bód-na)." },
    { id: 173, slang: true, en: "I'll think about it.", ru: "Я подумаю.", pronun: "Ya pa-dú-ma-yu.", literal: "I will-think.", note: "Often used to politely decline without saying no." },
    { id: 174, slang: true, en: "Maybe next time.", ru: "В следующий раз.", pronun: "F slyé-du-yush-chy raz.", literal: "The next time.", note: "" },
    { id: 175, slang: true, en: "I missed you!", ru: "Я по тебе скучал!", pronun: "Ya pa te-byé sku-chál!", literal: "I for you missed!", note: "Female speaker: скучала (sku-chá-la)." },
    { id: 176, slang: true, en: "How long has it been!", ru: "Сколько лет, сколько зим!", pronun: "Skól-ka lyet, skól-ka zim!", literal: "How many summers, how many winters!", note: "Classic Russian expression for long time no see." },
    { id: 177, slang: true, en: "You haven't changed at all!", ru: "Ты совсем не изменился!", pronun: "Ty sav-syém nye iz-me-níl-sya!", literal: "You not-at-all changed!", note: "Female: не изменилась (nye iz-me-ní-las')." },
    { id: 178, slang: true, en: "Take care of yourself!", ru: "Береги себя!", pronun: "Be-re-gí se-byá!", literal: "Guard yourself!", note: "A warm Russian farewell — more heartfelt than 'bye'." },
    { id: 179, slang: true, en: "That's life!", ru: "Такова жизнь.", pronun: "Ta-ka-vá zhizn'.", literal: "Such is life.", note: "" },
    { id: 180, slang: true, en: "Not my problem!", ru: "Не моя проблема!", pronun: "Nye ma-yá prab-lyé-ma!", literal: "Not my problem!", note: "" },
    { id: 181, slang: true, en: "I messed up / made a mistake.", ru: "Я облажался.", pronun: "Ya ab-la-zhál-sya.", literal: "I failed / blundered.", note: "Female: облажалась (ab-la-zhá-las'). Casual slang." },
    { id: 182, slang: true, en: "I'm freaking out.", ru: "Я в панике.", pronun: "Ya f pá-ni-kye.", literal: "I in panic.", note: "" },
    { id: 183, slang: true, en: "Calm down, it's okay.", ru: "Спокойно, всё хорошо.", pronun: "Spa-kóy-na, fsyo kha-ra-shó.", literal: "Calmly, everything good.", note: "" },
    { id: 184, slang: true, en: "What the heck?!", ru: "Что за ерунда?!", pronun: "Shto za ye-run-dá?!", literal: "What sort of nonsense?!", note: "A safe, non-vulgar expression of disbelief or frustration." },
    { id: 185, slang: true, en: "I totally forgot!", ru: "Я совсем забыл!", pronun: "Ya sav-syém za-býl!", literal: "I completely forgot!", note: "Female: забыла (za-bý-la)." },
    { id: 186, slang: true, en: "Remind me.", ru: "Напомни мне.", pronun: "Na-pómni mnye.", literal: "Remind me.", note: "" },
    { id: 187, slang: true, en: "Write it down.", ru: "Запиши это.", pronun: "Za-pi-shí é-ta.", literal: "Write-down this.", note: "" },
    { id: 188, slang: true, en: "Good job! / Well done!", ru: "Молодец!", pronun: "Ma-la-dyéts!", literal: "Good fellow!", note: "Works for all genders despite the masculine form. Very common praise." },
    { id: 189, slang: true, en: "Stop showing off.", ru: "Не выпендривайся.", pronun: "Nye vy-pyen-dri-vay-sya.", literal: "Don't show-off.", note: "A very colloquial phrase." },
    { id: 190, slang: true, en: "You're overthinking it.", ru: "Ты слишком много думаешь.", pronun: "Ty slísh-kam mnó-ga dú-ma-yesh'.", literal: "You too much think.", note: "" },
    { id: 191, slang: true, en: "Trust me.", ru: "Поверь мне.", pronun: "Pa-vyér' mnye.", literal: "Believe me.", note: "" },
    { id: 192, slang: true, en: "Promise?", ru: "Обещаешь?", pronun: "A-be-shchá-yesh'?", literal: "You-promise?", note: "" },
    { id: 193, slang: true, en: "I promise.", ru: "Обещаю.", pronun: "A-be-shchá-yu.", literal: "I promise.", note: "" },
    { id: 194, slang: true, en: "Just between us.", ru: "Только между нами.", pronun: "Tól'-ka myézh-du ná-mi.", literal: "Only between us.", note: "" },
    { id: 195, slang: true, en: "It's a secret.", ru: "Это секрет.", pronun: "É-ta sek-ryét.", literal: "This secret.", note: "" },
    { id: 196, slang: true, en: "I can't take it anymore.", ru: "Я больше не могу.", pronun: "Ya ból'-she nye ma-gú.", literal: "I more not can.", note: "" },
    { id: 197, slang: true, en: "That's the last straw!", ru: "Это последняя капля!", pronun: "É-ta pas-lyéd-nya-ya káp-lya!", literal: "This last drop!", note: "Russians say 'last drop', English says 'last straw'. Same meaning." },
    { id: 198, slang: true, en: "I'm done with this.", ru: "Я закончил с этим.", pronun: "Ya za-kón-chil s é-tim.", literal: "I finished with this.", note: "Female: закончила (za-kón-chi-la)." },
    { id: 199, slang: true, en: "It is what it is.", ru: "Что есть, то есть.", pronun: "Shto yest', to yest'.", literal: "What is, that is.", note: "" },
    { id: 200, slang: true, en: "No pain, no gain.", ru: "Без труда не вытащишь рыбку из пруда.", pronun: "Byez tru-dá nye vý-ta-shish' rýp-ku iz pru-dá.", literal: "Without effort you won't pull a fish from a pond.", note: "The full Russian proverb. Usually just the first part is said." },
];

// Merge into one master list
const ALL_CARDS = [...CARDS, ...SLANG];